import { describe, expect, it } from "vitest";
import { validateNif } from "./nif";

// Fixtures below are 8 seed digits + a checksum digit computed independently
// via the §5.7.2 mod-11 formula (verified by hand and by a throwaway script
// before being hardcoded here — not generated by calling validateNif).

describe("validateNif — accepted prefixes (checksum valid, entity type ok)", () => {
  it.each([
    ["500000000", "5 — collective person (company)"],
    ["600000001", "6 — public entity / administration"],
    ["710000006", "71 — non-resident collective entity"],
    ["720000009", "72 — investment fund"],
  ])("accepts %s (%s)", (nif) => {
    expect(validateNif(nif)).toEqual({ valid: true, nif });
  });

  it("tolerates formatting characters (spaces, dashes)", () => {
    expect(validateNif("500 000 000")).toEqual({ valid: true, nif: "500000000" });
    expect(validateNif("500-000-000")).toEqual({ valid: true, nif: "500000000" });
  });
});

describe("validateNif — rejected prefixes (checksum valid, wrong entity type)", () => {
  it.each([
    ["100000002", "1 — natural person"],
    ["200000004", "2 — natural person"],
    ["300000006", "3 — natural person"],
    ["450000001", "45 — natural person"],
    ["800000005", "8 — not on the accepted list"],
    ["900000007", "9 — not on the accepted list"],
    ["400000008", "4 — not on the accepted list (must not match the 45 rule)"],
  ])("rejects %s as not_business (%s)", (nif) => {
    expect(validateNif(nif)).toEqual({ valid: false, reason: "not_business" });
  });

  it("rejects 000000000: checksum passes trivially, but prefix is not a business entity", () => {
    expect(validateNif("000000000")).toEqual({ valid: false, reason: "not_business" });
  });
});

describe("validateNif — checksum failures", () => {
  it.each([
    "500000001", // valid prefix, last digit off by one from the correct 500000000
    "600000000",
    "710000000",
    "720000000",
  ])("rejects %s as checksum", (nif) => {
    expect(validateNif(nif)).toEqual({ valid: false, reason: "checksum" });
  });
});

describe("validateNif — format failures", () => {
  it.each([
    ["12345678", "too short"],
    ["1234567890", "too long"],
    ["", "empty"],
    ["abcdefghi", "non-numeric"],
  ])("rejects %s as format (%s)", (nif) => {
    expect(validateNif(nif)).toEqual({ valid: false, reason: "format" });
  });
});
