-- SóIT — tech_tags vocabulary seed (build spec §5.6)
--
-- A controlled vocabulary, seeded by us and not extendable by employers: a
-- vocabulary employers can extend stops being one. Aliases exist so the
-- posting form's autocomplete resolves "reactjs" and "react.js" to React.
-- Idempotent — safe to re-run as the list grows.

insert into tech_tags (slug, label, aliases) values
  -- Languages
  ('java', 'Java', '{}'),
  ('javascript', 'JavaScript', array['js']),
  ('typescript', 'TypeScript', array['ts']),
  ('python', 'Python', '{}'),
  ('csharp', 'C#', array['c-sharp','c#']),
  ('cpp', 'C++', array['c-plus-plus']),
  ('c', 'C', '{}'),
  ('go', 'Go', array['golang']),
  ('rust', 'Rust', '{}'),
  ('ruby', 'Ruby', '{}'),
  ('php', 'PHP', '{}'),
  ('kotlin', 'Kotlin', '{}'),
  ('swift', 'Swift', '{}'),
  ('scala', 'Scala', '{}'),
  ('elixir', 'Elixir', '{}'),
  ('dart', 'Dart', '{}'),
  ('groovy', 'Groovy', '{}'),
  ('perl', 'Perl', '{}'),
  ('lua', 'Lua', '{}'),
  ('sql', 'SQL', '{}'),
  ('bash', 'Bash', array['shell']),
  ('r', 'R', '{}'),
  -- Frontend
  ('react', 'React', array['reactjs','react.js']),
  ('nextjs', 'Next.js', array['next']),
  ('vue', 'Vue', array['vuejs','vue.js']),
  ('nuxt', 'Nuxt', '{}'),
  ('angular', 'Angular', array['angularjs']),
  ('svelte', 'Svelte', '{}'),
  ('sveltekit', 'SvelteKit', '{}'),
  ('astro', 'Astro', '{}'),
  ('html', 'HTML', array['html5']),
  ('css', 'CSS', array['css3']),
  ('sass', 'Sass', array['scss']),
  ('tailwindcss', 'Tailwind CSS', array['tailwind']),
  ('redux', 'Redux', '{}'),
  ('vite', 'Vite', '{}'),
  ('webpack', 'Webpack', '{}'),
  ('storybook', 'Storybook', '{}'),
  -- Backend
  ('spring-boot', 'Spring Boot', array['springboot']),
  ('spring', 'Spring', '{}'),
  ('quarkus', 'Quarkus', '{}'),
  ('nodejs', 'Node.js', array['node']),
  ('express', 'Express', array['expressjs']),
  ('nestjs', 'NestJS', array['nest']),
  ('django', 'Django', '{}'),
  ('flask', 'Flask', '{}'),
  ('fastapi', 'FastAPI', '{}'),
  ('rails', 'Ruby on Rails', array['ruby-on-rails']),
  ('laravel', 'Laravel', '{}'),
  ('symfony', 'Symfony', '{}'),
  ('dotnet', '.NET', array['dot-net','net-core']),
  ('aspnet', 'ASP.NET', array['asp-net']),
  ('hibernate', 'Hibernate', '{}'),
  ('graphql', 'GraphQL', '{}'),
  ('rest', 'REST', array['rest-api']),
  ('grpc', 'gRPC', '{}'),
  ('kafka', 'Kafka', array['apache-kafka']),
  ('rabbitmq', 'RabbitMQ', '{}'),
  ('micronaut', 'Micronaut', '{}'),
  -- Mobile
  ('android', 'Android', '{}'),
  ('ios', 'iOS', '{}'),
  ('flutter', 'Flutter', '{}'),
  ('react-native', 'React Native', array['reactnative']),
  ('swiftui', 'SwiftUI', '{}'),
  ('jetpack-compose', 'Jetpack Compose', '{}'),
  ('ionic', 'Ionic', '{}'),
  ('xamarin', 'Xamarin', '{}'),
  -- Cloud & infra
  ('aws', 'AWS', array['amazon-web-services']),
  ('azure', 'Azure', array['microsoft-azure']),
  ('gcp', 'Google Cloud', array['google-cloud-platform']),
  ('terraform', 'Terraform', '{}'),
  ('pulumi', 'Pulumi', '{}'),
  ('kubernetes', 'Kubernetes', array['k8s']),
  ('docker', 'Docker', '{}'),
  ('helm', 'Helm', '{}'),
  ('openshift', 'OpenShift', '{}'),
  ('serverless', 'Serverless', '{}'),
  ('lambda', 'AWS Lambda', '{}'),
  ('nginx', 'Nginx', '{}'),
  ('linux', 'Linux', '{}'),
  ('cloudformation', 'CloudFormation', '{}'),
  -- DevOps & SRE
  ('jenkins', 'Jenkins', '{}'),
  ('gitlab-ci', 'GitLab CI', '{}'),
  ('github-actions', 'GitHub Actions', '{}'),
  ('argocd', 'Argo CD', '{}'),
  ('ansible', 'Ansible', '{}'),
  ('puppet', 'Puppet', '{}'),
  ('prometheus', 'Prometheus', '{}'),
  ('grafana', 'Grafana', '{}'),
  ('datadog', 'Datadog', '{}'),
  ('elk', 'ELK Stack', array['elastic-stack']),
  ('opentelemetry', 'OpenTelemetry', array['otel']),
  ('git', 'Git', '{}'),
  ('ci-cd', 'CI/CD', array['cicd']),
  -- Data
  ('postgresql', 'PostgreSQL', array['postgres']),
  ('mysql', 'MySQL', '{}'),
  ('sql-server', 'SQL Server', array['mssql']),
  ('oracle', 'Oracle', '{}'),
  ('mongodb', 'MongoDB', array['mongo']),
  ('redis', 'Redis', '{}'),
  ('cassandra', 'Cassandra', '{}'),
  ('dynamodb', 'DynamoDB', '{}'),
  ('elasticsearch', 'Elasticsearch', '{}'),
  ('snowflake', 'Snowflake', '{}'),
  ('bigquery', 'BigQuery', '{}'),
  ('redshift', 'Redshift', '{}'),
  ('databricks', 'Databricks', '{}'),
  ('spark', 'Apache Spark', array['pyspark']),
  ('airflow', 'Airflow', array['apache-airflow']),
  ('dbt', 'dbt', '{}'),
  ('power-bi', 'Power BI', array['powerbi']),
  ('tableau', 'Tableau', '{}'),
  ('looker', 'Looker', '{}'),
  ('pandas', 'pandas', '{}'),
  ('numpy', 'NumPy', '{}'),
  -- AI & ML
  ('machine-learning', 'Machine Learning', array['ml']),
  ('deep-learning', 'Deep Learning', '{}'),
  ('tensorflow', 'TensorFlow', '{}'),
  ('pytorch', 'PyTorch', '{}'),
  ('scikit-learn', 'scikit-learn', array['sklearn']),
  ('nlp', 'NLP', '{}'),
  ('computer-vision', 'Computer Vision', '{}'),
  ('llm', 'LLM', array['large-language-models']),
  ('mlops', 'MLOps', '{}'),
  -- Testing
  ('junit', 'JUnit', '{}'),
  ('pytest', 'pytest', '{}'),
  ('jest', 'Jest', '{}'),
  ('cypress', 'Cypress', '{}'),
  ('playwright', 'Playwright', '{}'),
  ('selenium', 'Selenium', '{}'),
  ('cucumber', 'Cucumber', '{}'),
  ('k6', 'k6', '{}'),
  ('testng', 'TestNG', '{}'),
  -- Security
  ('oauth', 'OAuth', array['oauth2']),
  ('oidc', 'OpenID Connect', '{}'),
  ('saml', 'SAML', '{}'),
  ('owasp', 'OWASP', '{}'),
  ('penetration-testing', 'Penetration Testing', array['pentesting']),
  ('iso-27001', 'ISO 27001', '{}'),
  ('cryptography', 'Cryptography', '{}'),
  -- Enterprise
  ('salesforce', 'Salesforce', '{}'),
  ('apex', 'Apex', '{}'),
  ('lwc', 'Lightning Web Components', '{}'),
  ('sap', 'SAP', '{}'),
  ('sap-abap', 'SAP ABAP', array['abap']),
  ('servicenow', 'ServiceNow', '{}'),
  ('dynamics-365', 'Dynamics 365', '{}'),
  ('sharepoint', 'SharePoint', '{}'),
  ('mulesoft', 'MuleSoft', '{}'),
  ('outsystems', 'OutSystems', '{}'),
  -- Practices
  ('agile', 'Agile', '{}'),
  ('scrum', 'Scrum', '{}'),
  ('kanban', 'Kanban', '{}'),
  ('tdd', 'TDD', '{}'),
  ('ddd', 'DDD', array['domain-driven-design']),
  ('microservices', 'Microservices', '{}'),
  ('event-driven', 'Event-Driven Architecture', '{}'),
  ('clean-architecture', 'Clean Architecture', '{}'),
  ('leadership', 'Leadership', '{}')
on conflict (slug) do update
  set label = excluded.label, aliases = excluded.aliases;
